[workspace]
authors = ["James Bacon <james.bacon@seh.ox.ac.uk>", "William Clarke <william.clarke@ndcn.ox.ac.uk>"]
channels = ["https://prefix.dev/conda-forge", "https://fsl.fmrib.ox.ac.uk/fsldownloads/fslconda/public/"]
name = "GIRF_PE_Python"
platforms = ["osx-arm64", "linux-64"]
version = "0.1.0"

[tasks]
gen-seq = "python Pypulseq_GIRF_PE.py"
proc-data = "python GIRF_PE_Processing.py"
get-girf = "python PE_script_OptimizedGIRFCalculation.py"

[dependencies]
python = "3.12.*"
numpy = ">=2.2.4,<3"
matplotlib = ">=3.10.1,<4"
fsl_mrs = ">=2.4.3,<3"
setuptools = "<81"
scipy = ">=1.17.1,<2"

[pypi-dependencies]
pypulseq = { git = "https://github.com/imr-framework/pypulseq.git" }
twixtools = ">=0.23, <0.24"
